package com.noe.hypercube;

import com.dropbox.core.DbxAuthFinish;
import com.dropbox.core.DbxException;
import com.dropbox.core.DbxWebAuthNoRedirect;
import org.apache.log4j.Logger;

import javax.swing.*;
import java.io.IOException;

public class Authentication {

    private static final Logger LOG = Logger.getLogger(Authentication.class);

    DbxWebAuthNoRedirect dbxWebAut;

    public String requestAccessToken() throws IOException, DbxException {
        LOG.debug("Authentication started");
        String authorizeUrl = dbxWebAut.start();
        LOG.info("Authorization URL: " + authorizeUrl);
        JTextArea textarea= new JTextArea("Go to: " + authorizeUrl);
        textarea.setEditable(true);
        JOptionPane.showMessageDialog(null, textarea, "Confirm Dropbox using", JOptionPane.ERROR_MESSAGE);

        String clientKey = JOptionPane.showInputDialog(null, "Please copy here the access key generated by Dropbox");

        DbxAuthFinish authFinish = dbxWebAut.finish(clientKey);
        LOG.debug("Authentication finished");
        return authFinish.accessToken;
    }

}
