package com.noe.hypercube.ui.action;

public enum FileAction {
    COPY, MOVE, DELETE, NEW_FOLDER, UPLOAD, DOWNLOAD, MOVE_UPLOAD, MOVE_DOWNLOAD, NEW_CLOUD_FOLDER, CLOUD_COPY, CLOUD_MOVE, CLOUD_DELETE, CLOSE, EDIT
}
